### ISSUE TITLE
Cannot form weak reference to instance (0x7f81547ccfc0) of class UIInputSetHostView.

### ISSUE THREAD

**Issue by AironMore** [ParsifalC/NetEaseBaymaxDemo#4]
在本地工程中测试KVO防护功能的时候，发现与 YYTextKeyboardManager.h 有所冲突，会报错
Cannot form weak reference to instance (0x7f81547ccfc0) of class UIInputSetHostView. It is possible that this object was over-released, or is in the process of deallocation.

代码如下：
`
- (void)addToKeyboardView:(UIView *)keyboardView {
    if (_keyboardView == keyboardView) return;
    if (_keyboardView) {
        [self removeFrameObserver];
        objc_setAssociatedObject(_keyboardView, &_YYTextKeyboardViewFrameObserverKey, nil, OBJC_ASSOCIATION_RETAIN_NONATOMIC);
    }
    _keyboardView = keyboardView;
    if (keyboardView) {
        [self addFrameObserver];
    }
    objc_setAssociatedObject(keyboardView, &_YYTextKeyboardViewFrameObserverKey, self, OBJC_ASSOCIATION_RETAIN_NONATOMIC);
}

- (void)removeFrameObserver {
    [_keyboardView removeObserver:self forKeyPath:@"frame"];
    [_keyboardView removeObserver:self forKeyPath:@"center"];
    [_keyboardView removeObserver:self forKeyPath:@"bounds"];
    [_keyboardView removeObserver:self forKeyPath:@"transform"];
    _keyboardView = nil;
}

- (void)addFrameObserver {
    if (!_keyboardView) return;
    [_keyboardView addObserver:self forKeyPath:@"frame" options:kNilOptions context:NULL];
    [_keyboardView addObserver:self forKeyPath:@"center" options:kNilOptions context:NULL];
    [_keyboardView addObserver:self forKeyPath:@"bounds" options:kNilOptions context:NULL];
    [_keyboardView addObserver:self forKeyPath:@"transform" options:kNilOptions context:NULL];
}

- (void)dealloc {
    [self removeFrameObserver];
}
`
keyboardView的声明是这样的   __unsafe_unretained UIView *_keyboardView;
是不是因为 _unsafe_unretained 的原因导致的问题？
如果是的话 要怎么做才能避免呢？

**Comment by ParsifalC** [comment]
现在再试试呢？ @AironMore

**Comment by AironMore** [comment]
@ParsifalC 
不行 会直接崩溃。
我本地解决的方案是 
将 @property (weak, nonatomic) id weakObservedObject;
修改为：@property (unsafe_unretained, nonatomic) id weakObservedObject;

不知道这样做 是否会有问题？

**Comment by ParsifalC** [comment]
是最新的代码吗？我昨天有提交。Best Regards  
________________________
Parsifal Zhang (张明玮)
iOS Developer  
Mobile:158-5815-4669
Email:zmw@izmw.me
GitHub:https://github.com/ParsifalC
            在2017年06月13日 10:54，AironMore 写道： @ParsifalC
不行 会直接崩溃。
我本地解决的方案是
将 @property (weak, nonatomic) id weakObservedObject;
修改为：@property (unsafe_unretained, nonatomic) id weakObservedObject;
不知道这样做 是否会有问题？

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/ParsifalC/NetEaseBaymaxDemo","title":"ParsifalC/NetEaseBaymaxDemo","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/ParsifalC/NetEaseBaymaxDemo"}},"updates":{"snippets":[{"icon":"PERSON","message":"@AironMore in #4: @ParsifalC \r\n不行 会直接崩溃。\r\n我本地解决的方案是 \r\n将 @property (weak, nonatomic) id weakObservedObject;\r\n修改为：@property (unsafe_unretained, nonatomic) id weakObservedObject;\r\n\r\n不知道这样做 是否会有问题？"}],"action":{"name":"View Issue","url":"https://github.com/ParsifalC/NetEaseBaymaxDemo/issues/4#issuecomment-307991882"}}}

**Comment by AironMore** [comment]
是的 13小时以前的 
就是在removeObserve 里删除了之前的 if(!self.kvoDelegate) 那一段代码。

**Comment by ParsifalC** [comment]
能提供个demo吗？我排查下。Best Regards  
________________________
Parsifal Zhang (张明玮)
iOS Developer  
Mobile:158-5815-4669
Email:zmw@izmw.me
GitHub:https://github.com/ParsifalC
            在2017年06月13日 14:04，AironMore 写道： 是的 13小时以前的
就是在removeObserve 里删除了之前的 if(!self.kvoDelegate) 那一段代码。

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/ParsifalC/NetEaseBaymaxDemo","title":"ParsifalC/NetEaseBaymaxDemo","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/ParsifalC/NetEaseBaymaxDemo"}},"updates":{"snippets":[{"icon":"PERSON","message":"@AironMore in #4: 是的 13小时以前的 \r\n就是在removeObserve 里删除了之前的 if(!self.kvoDelegate) 那一段代码。"}],"action":{"name":"View Issue","url":"https://github.com/ParsifalC/NetEaseBaymaxDemo/issues/4#issuecomment-308015927"}}}

**Comment by AironMore** [comment]
加个YYtext 随便用个 textField就出现了
需要的话 也可以把我手头的给你，不过要等到明天了

**Comment by AironMore** [comment]
是YYTextKeyboardManager

**Comment by ParsifalC** [comment]
@AironMore 你提供个复现的demo给我吧，我debug下。

**Comment by AironMore** [comment]
@ParsifalC 
你加我QQ 我发给你
